export const steps = [
    ['search', 'Find your series', 'Connect Telegram, then choose a joined channel or follow a supported bot result.', 'Missing a channel? Switch to All channels.'],
    ['film', 'Choose your episodes', 'Pick a quality and codec. Select a whole season or just the episodes you want.', 'Unverified lets you choose files with uncertain metadata.'],
    ['download', 'Start your collection', 'Choose your Download or Watch folder, then download. Open completed files from Finished downloads.', 'Pause and resume from Downloads whenever you need.'],
  ];
export const questions = [
    ['What do Ongoing, Finished and Remove from history mean?', 'Ongoing shows downloads that are active, queued, paused or need attention. Finished shows completed files, newest first. Remove from history and Clear finished history keep your files on disk, but the app forgets those episodes and Select missing may offer them again. To delete a disk file, open File details and choose Move file to Recycle Bin, then confirm.'],
    ['Why does a file say Checking or Transferring?', 'The Telegram download is finished. Checking calculates a checksum; Transferring saves the file in your chosen folder and verifies the copy. New downloads can start during these stages. Disk work runs one file at a time; downloads wait if the finishing backlog reaches its limit.'],
    ['How are my files organised?', 'Recognised episodes go into season folders. After all queued files for a season finish, filenames follow the majority separator style: dots, spaces, underscores or dashes. Extensions and tags such as WEB-DL stay intact. Ties keep the original style; paused or failed jobs delay naming. Unverified files keep original names in an Unverified folder. Filename collisions offer a retry in File details.'],
    ['What do Verified and Unverified mean?', 'Verified means the episode and quality metadata were recognised; it does not guarantee language, subtitles or content. Archive defaults to 720p HEVC and Watch prefers 1080p. Choose from formats actually found in the channel; Auto codec prefers HEVC. Check source filenames and play a sample for audio and subtitles.'],
    ['How does bot discovery work?', 'Use Change series to find the supported MovieClubFamily search group. Search for a title or paste a private message link. A single series result continues automatically; choose when several appear. The app follows supported bot buttons, sends Start and joins the series channel. Subscription help lets you select required channels and retry. Unsupported buttons and approval-only invites may still need Telegram.'],
    ['What if I pause, clear the queue or close the app?', 'Pause retains progress for resuming. Remove from queue and Clear queue delete temporary data; adding those downloads again starts from scratch. Completed files and lifetime usage totals are kept. Closing pauses downloads even when the app stays in the tray; file verification and transfers finish safely. After a restart, resume paused jobs. Your saved Telegram session reconnects when valid; sign in again if it expires. Reconnect missing drives at their original location. Downloads need the computer awake.'],
    ['Can I clear history without deleting videos?', 'Yes. Clear app data in Settings removes history and the selected series while keeping downloaded media and partial files. Delete media separately from Finished downloads with confirmation. Delete all pending only removes unfinished queue entries. Settings can clean up unused partial files. Different existing media files are never overwritten; staging and the destination both need free space.'],
    ['Can I follow new episodes automatically?', 'Watch series checks new posts hourly while the app runs. Choose notifications or automatic queuing with your selected quality and folder. Select missing compares the channel against app-managed saved files in the current mode. Set download hours, bandwidth and simultaneous downloads in Settings. Requests already in flight can finish after scheduled hours end.'],
  ];
